# Generated by Django 4.2.5 on 2024-08-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(choices=[('IN', 'Indian'), ('FR', 'Foreign')], max_length=2)),
                ('category', models.CharField(choices=[('AUTHOR', 'Author'), ('STUDENT', 'Student'), ('PROF_ATN', 'Professional Attende'), ('AUTHOR_ATN', 'Author Attende'), ('TUTORIAL', 'Tutorial')], max_length=15)),
                ('payment_check', models.BooleanField(default=False)),
            ],
        ),
    ]
