# Generated by Django 5.0.3 on 2024-08-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_attende'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text to display in the ticker', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='attende',
            name='category',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('STUDENT', 'Student'), ('PROF_ATN', 'Professional Attende'), ('AUTHOR_ATN', 'Author Attende'), ('TUTORIAL', 'Tutorial')], default='Student', max_length=15),
        ),
        migrations.AlterField(
            model_name='attende',
            name='nationality',
            field=models.CharField(choices=[('IN', 'Indian'), ('FR', 'Foreign')], default='Indian', max_length=2),
        ),
    ]
