# Generated by Django 5.0.3 on 2024-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tickertext_alter_attende_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickertext',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the announcement is active'),
        ),
    ]
