# Generated by Django 5.0.3 on 2024-08-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_tickertext_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickertext',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tickertext',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
