version: '3'

services:
  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    env_file:
      - .env
    expose:
      - '3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pedesnet
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  web:
    build: ./web
    command: bash -c "python manage.py migrate && gunicorn -w 4 -b :8000 pedes.wsgi:application"
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static:/code/static
      - media:/code/media
    networks:
      - pedesnet
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '127.0.0.1:8000']
      timeout: 30s
      retries: 20

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/web/static
      - media:/web/media
    networks:
      - pedesnet
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy

volumes:
  static:
  media:
  dbdata:

networks:
  pedesnet:
