version: '3'

services:
  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    env_file:
      - .env
    expose:
      - '3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pedesnet
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      timeout: 20s
      retries: 10

  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - static:/code/prod_static
      - media:/code/prod_media
      - ./web:/code
    networks:
      - pedesnet
    depends_on:
      db:
        condition: service_healthy

volumes:
  static:
  media:
  dbdata:

networks:
  pedesnet:
