# Generated by Django 4.2.5 on 2024-08-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_attende'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attende',
        ),
    ]
